#!/bin/sh

echo -e "\033[0;32mInstalling Vim & NeoVim...\033[0;37m"
sudo apt install vim
sudo snap install nvim --classic

echo -e "\033[0;32mInstalling tmux...\033[0;37m"
sudo apt install tmux

# Install plug.vim for NeoVim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim -c ':PlugInstall|q|q'

# Coc.nvim
gnome-terminal -- nvim -c ':TSInstall bash vim yaml'

